# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6691fb44cb52db8028713d32edd03cd9654dc976f22fb273849ea91980b9a6a0795d261aee5af429af485a2c61836f6c8a827bb4acd173a26922e63db6c9f705

test:
  secret_key_base: 28b038d2c8d9468723f57fd501ee5c0882b43210de8d52bb40c59b1be0b1e556a4b28704fbaae91de872ab83557a4704578dc5ac25509af2d794b4f4bee2747c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
